{% set name = "uppasd" %}
{% set version = "v6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UppASD/UppASD/releases/download/{{ version }}/{{ version }}.tar.gz
  sha256: f483bb6e0a5c75820e4a3d38894c40557548777160eabd3c152c8c356e6ca8ed
  patches:
    - binary-name.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - fftw         # [not win]
  host:
    - fftw         # [not win]
    - libblas
    - liblapack
    #- vs2015_runtime  # [win]
  #run:
    #- openblas # [not win]
    #- mkl      # [win]
    #- vs2015_runtime  # [win]

test:
  source_files:
    - examples/SimpleSystems/bccFe
  commands:
    - sd  # [build_platform == target_platform]
    - cd examples/SimpleSystems/bccFe && sd  # [build_platform == target_platform]

outputs:
  # For now only distribute the binary but not the static library. Building a shared
  # library would be preferable but seems to not be straightforward for UppASD (some
  # things are hardcoded in their CMakeLists.txt).
  - name: uppasd
    files:
      include:
        - bin/sd
      exclude:
        - lib/libasdlib.a

about:
  home: https://github.com/UppASD/UppASD
  summary: 'Atomistic spin dynamics and Monte Carlo simulations'
  description: |
    The UppASD package is a simulation tool for
    atomistic spin dynamics and Monte Carlo simulations
    of Heisenberg spin systems. 
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  doc_url: https://uppasd.github.io/UppASD-manual

extra:
  recipe-maintainers:
    - lang-m
