# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe
# If your package is python based, we recommend using Grayskull to generate it instead:
# https://github.com/conda-incubator/grayskull

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 16 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "uppasd" %}
{% set version = "v6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UppASD/UppASD/releases/download/{{ version }}/{{ version }}.tar.gz
  sha256: f483bb6e0a5c75820e4a3d38894c40557548777160eabd3c152c8c356e6ca8ed
  patches:
    - binary-name.patch

build:
  number: 0

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx', 'fortran', among others
    - {{ compiler('fortran') }}
    # this is necessary for all compiled recipes
    - {{ stdlib('c') }}
    - cmake
    - make  # [not win]
    - ninja
  host:
    - fftw
    - libblas
    - liblapack
    - libgomp
    - vs2015_runtime  # [win]
  run:
    - libgomp
    - openblas # [not win]
    - mkl      # [win]
    - vs2015_runtime  # [win]

test:
  source_files:
    - examples/SimpleSystems/bccFe
  commands:
    - ls -l; sd
    - cd examples/SimpleSystems/bccFe && sd
  # Some packages might need a `test/commands` key to check CLI.

about:
  home: https://github.com/simplejson/simplejson
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'
  description: |
    simplejson is a simple, fast, complete, correct and extensible
    JSON <https://json.org> encoder and decoder for Python 2.5+ and
    Python 3.3+. It is pure Python code with no dependencies, but includes
    an optional C extension for a serious speed boost.
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  # The doc_url and dev_url are optional.
  doc_url: https://simplejson.readthedocs.io/
  dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - LisaSimpson
    - LandoCalrissian
